### ISSUE TITLE
Include timestamp received and sender IP in the reply.

### ISSUE THREAD

**Issue by relsqui** [PSU-CS-300-Fall2015/taunet-utils#1]
Requested by request :) https://github.com/PSU-CS-300-Fall2015/taurus/issues/6#issuecomment-160807749

**Comment by BartMassey** [comment]
A reasonable enhancement request. Will work on it today.

**Comment by BartMassey** [comment]
Fixed. The first line of the response now contains the date, source IP and source port of the echo request.
